name: operaciones_flutter
description: Sistema de Operaciones LaVianda - Gestión en tiempo real con mapas, formularios y tracking

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  
  # State Management (BLoC)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Navigation
  go_router: ^13.0.0
  
  # API & Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # WebSockets (Laravel Echo + Pusher)
  pusher_channels_flutter: ^2.2.1
  web_socket_channel: ^2.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  
  # Camera & Images
  image_picker: ^1.0.7
  camera: ^0.10.5+7
  photo_view: ^0.14.0
  image_cropper: ^5.0.1
  
  # Signature
  signature: ^5.4.1
  hand_signature: ^3.0.2
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  syncfusion_flutter_pdfviewer: ^24.1.41
  
  # File Management
  file_picker: ^6.1.1
  open_file: ^3.3.2
  path: ^1.8.3
  
  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # Date & Time
  intl: ^0.18.1
  timeago: ^3.6.0
  
  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  
  # Forms & Validation
  formz: ^0.6.1
  mask_text_input_formatter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
