name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Create local.properties
      run: |
        echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
        
    - name: Fix geolocator_android build.gradle bug
      run: |
        # Definir propiedades Flutter globalmente para evitar el bug de geolocator_android
        cat >> android/gradle.properties << 'EOF'
        
        # Flutter SDK properties (fix for geolocator_android 4.6.2 bug)
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Patch geolocator_android build.gradle
      run: |
        # Encontrar y parchear el build.gradle de geolocator_android
        GEOLOCATOR_PATH=$(find ~/.pub-cache/hosted/pub.dev -name "geolocator_android-4.6.2" -type d | head -1)
        if [ -n "$GEOLOCATOR_PATH" ]; then
          BUILD_FILE="$GEOLOCATOR_PATH/android/build.gradle"
          if [ -f "$BUILD_FILE" ]; then
            echo "Patching $BUILD_FILE"
            # Reemplazar flutter.compileSdkVersion con 34
            sed -i 's/compileSdkVersion flutter\.compileSdkVersion/compileSdkVersion 34/g' "$BUILD_FILE"
            sed -i 's/minSdkVersion flutter\.minSdkVersion/minSdkVersion 21/g' "$BUILD_FILE"
            sed -i 's/targetSdkVersion flutter\.targetSdkVersion/targetSdkVersion 34/g' "$BUILD_FILE"
            echo "Geolocator_android patched successfully"
          fi
        fi
      
    - name: Build APK (Debug)
      run: flutter build apk --debug
      
    - name: Build APK (Release)
      run: flutter build apk --release
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        tag: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          🚀 Nueva versión de La Vianda Operaciones
          
          📱 APKs generados:
          - app-debug.apk (para pruebas)
          - app-release.apk (para producción)
          
          🔗 Backend: https://operaciones.lavianda.com.co
        token: ${{ secrets.GITHUB_TOKEN }}
